<?php
	if (strstr($_SERVER['HTTP_USER_AGENT'], 'Chrome/'))
	{
		die('Geen Chrome! Chrome speelt vals!!');
	}
	header('Content-Type: text/plain; charset=utf-16');
?>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam viverra laoreet eros, quis feugiat neque venenatis bibendum. Ut mi leo, posuere et condimentum ac, tristique luctus ante. Nunc purus ipsum, facilisis in faucibus non, porttitor eget ligula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque justo tortor, commodo vitae convallis quis, vulputate sed nibh. Aenean in malesuada lorem. Quisque posuere tempus ornare.
<?php echo "\x00\x0A"; ?>
Cras vulputate, ante sed congue imperdiet, eros augue dignissim sem, id eleifend nisi dui at neque. Maecenas elit arcu, egestas eget congue ut, tincidunt ut lacus. Curabitur eget volutpat dui. Sed posuere euismod leo, nec porttitor eros ultrices eget. Nulla facilisi. Aliquam tempor congue dolor id suscipit. In et neque felis, eu iaculis risus. Cras id velit tortor. Ut ut augue diam, sit amet adipiscing massa. Duis metus sapien, mattis sit amet adipiscing luctus, molestie non tortor. Etiam scelerisque consequat arcu, vitae pulvinar orci ullamcorper ut. Curabitur dictum laoreet lectus non convallis. Nulla facilisi. Nullam ornare viverra enim, ac vulputate ligula blandit a. Nunc pulvinar purus id massa viverra a faucibus metus scelerisque. Cras elementum mattis erat, sed aliquam enim condimentum vitae.
<?php echo "\x00\x0A"; ?>
Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis ullamcorper feugiat nibh, vel hendrerit purus commodo et. Phasellus venenatis urna et metus pulvinar vulputate et eget odio. Duis volutpat venenatis fringilla. Quisque nunc lorem, egestas sollicitudin euismod sit amet, sodales eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum augue ante, gravida eu ullamcorper ac, varius eget nulla. Fusce fermentum cursus tellus, a viverra neque congue eu. Suspendisse arcu erat, tempus eu rhoncus quis, ultricies ac neque. Praesent vel diam velit. Sed lobortis placerat dui, eu tincidunt ligula feugiat ut. Ut risus nulla, congue vel rutrum vitae, gravida sit amet est. Proin tincidunt placerat eros, in ornare tellus bibendum non.
<?php echo "\x00\x0A"; ?>
Donec ante sem, tempor in convallis sed, consectetur non odio. Morbi nec sapien urna, vitae aliquam neque. Suspendisse facilisis consequat tortor eu facilisis. Donec ut purus turpis, eget vehicula odio. In egestas congue nunc nec molestie. In non eros in nibh rutrum dapibus ut nec tellus. Nullam euismod lacus eget massa porta pellentesque. Maecenas fermentum blandit neque a ultrices. Maecenas quis enim ut ipsum laoreet venenatis eget sed eros. Nulla facilisi. Suspendisse convallis mi ac eros imperdiet feugiat.
<?php echo "\x00\x0A"; ?>
Curabitur ac orci risus, vel gravida sapien. Morbi facilisis, mi faucibus hendrerit venenatis, tortor justo tincidunt massa, eget vulputate libero libero id nisl. Proin eget tellus quam. Aliquam non turpis mauris. Aliquam ante augue, tincidunt eget porta at, pharetra id nunc. Fusce pharetra venenatis aliquam. Quisque rhoncus, libero vitae sodales faucibus, metus mi tincidunt nibh, quis porttitor leo lacus non arcu. Nullam rhoncus, metus eu tristique tempus, dolor sem dapibus elit, vitae sollicitudin lectus nisi cursus urna. Nam eget diam sed sapien sodales vulputate. Morbi sollicitudin tristique nisi, lobortis pharetra nunc fermentum quis. Integer non odio in mi sodales accumsan. Pellentesque vel ante non lectus egestas adipiscing ac eget ligula.
<?php echo "\x00\x0A"; ?>
Integer risus ipsum, vestibulum id tristique quis, auctor ac justo. Sed eu mauris mauris. Curabitur molestie lacus vel libero malesuada placerat. In at velit metus, nec ultrices nulla. Proin placerat ipsum eros. Etiam sapien enim, mattis vitae tincidunt at, tincidunt ut ligula. Ut vel risus est, quis interdum libero. Integer at tellus vitae ipsum aliquam mollis sed id metus. Praesent ac ante nulla, tincidunt hendrerit leo. Nam quis enim leo, non sodales magna. Etiam odio purus, scelerisque blandit adipiscing eu, vehicula ac mauris. Vestibulum sed ipsum nec purus posuere rhoncus id sed nisl. Cras quis eros ut odio venenatis sodales a at tellus. Mauris dignissim molestie odio quis commodo. Phasellus blandit pulvinar sodales. Ut fermentum purus eu arcu sagittis lacinia.
<?php echo "\x00\x0A"; ?>
Cras a eros justo. Mauris a est augue. Sed ut nisl hendrerit ipsum suscipit vehicula. In eu orci leo. Vivamus vel quam quis massa sodales suscipit. Aliquam quis nisi quam. Sed ut dolor ligula. Phasellus sollicitudin ornare risus, id dapibus nunc ultricies ut. Praesent vehicula nunc in diam commodo viverra. Fusce dolor nulla, suscipit quis fringilla quis, tristique vitae nisl. Fusce auctor lacus a neque pellentesque commodo eget sit amet felis. Maecenas neque odio, tempor a facilisis nec, vulputate eu tortor. Nulla facilisi. Curabitur vel ante sed velit porttitor vehicula. Suspendisse volutpat risus et tellus consectetur eu sodales eros vulputate.
<?php echo "\x00\x0A"; ?>
Pellentesque sit amet quam quis lorem luctus accumsan ut at felis. Aenean lacinia iaculis orci et ornare. Donec a felis id dui pellentesque consequat. Suspendisse fringilla, purus ac mollis feugiat, magna arcu iaculis leo, nec tincidunt libero urna eget dolor. Nullam euismod mi id libero dictum interdum. Nulla consequat lobortis eros, at imperdiet ipsum dictum ut. Donec consectetur justo vitae tortor porta semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus at orci non quam dapibus faucibus eu eu quam. Nam a bibendum odio. Integer non fermentum augue. Duis luctus elementum sodales. Sed iaculis, metus in eleifend porta, mi lectus vehicula risus, non rutrum nisi leo ac augue. In hac habitasse platea dictumst. Integer varius nibh non dui convallis ultricies feugiat felis ultricies.
<?php echo "\x00\x0A"; ?>
Quisque auctor nisl sed turpis vulputate in scelerisque augue lacinia. Vestibulum congue vulputate odio in pretium. Curabitur vel risus enim, ut convallis velit. Donec in lectus ut mi ornare cursus sit amet ac lectus. Duis auctor sapien augue. Donec molestie tincidunt consectetur. Ut suscipit, nibh a ultrices dictum, justo risus consequat ante, sed dignissim risus metus a justo. Etiam nec sollicitudin elit. Curabitur dolor eros, lobortis a consectetur eu, porta non metus. Morbi dictum felis at magna posuere tristique. Cras eget dolor vel elit consequat rhoncus.
<?php echo "\x00\x0A"; ?>
Maecenas nisi enim, mattis quis bibendum sit amet, condimentum eget mauris. Vivamus sed felis nulla. Phasellus lobortis eros vitae eros dapibus sit amet mattis mi aliquam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla in metus velit, eget aliquet neque. Nulla molestie orci at tellus bibendum sed tincidunt metus consectetur. Mauris luctus dapibus mi eget tincidunt. Duis facilisis, diam non accumsan interdum, turpis augue dignissim turpis, id luctus arcu velit et quam. Ut purus sapien, auctor nec tempus at, ullamcorper ac enim. Aliquam ullamcorper erat eget lacus vestibulum id pharetra quam sollicitudin. Praesent sed lorem et neque convallis faucibus ac ac orci. Maecenas ac arcu vel velit gravida egestas eu vehicula nisl.
<?php echo "\x00\x0A"; ?>
Aliquam commodo molestie lectus, sit amet iaculis tortor dignissim non. Etiam sit amet est nunc, eu vehicula lorem. Vestibulum nec ante magna. Integer sed elementum nibh. Nullam vestibulum luctus neque at dapibus. Suspendisse eget pretium nibh. Suspendisse varius rutrum eros. In mauris velit, mattis id condimentum et, feugiat at justo. Maecenas nec arcu justo, quis venenatis elit. Morbi nec velit vitae libero aliquam tristique ut vitae nunc. Curabitur justo nibh, venenatis eu eleifend dapibus, feugiat ut ligula.
<?php echo "\x00\x0A"; ?>
Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur adipiscing massa at arcu facilisis ut ultrices orci elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras lorem dui, consectetur eget scelerisque et, facilisis id nibh. Ut nunc orci, congue at consequat et, ornare eu sapien. In porttitor libero ut ipsum ornare ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus nisi massa, dapibus at malesuada ut, varius quis nisi. Fusce pretium massa non neque tempus pretium ultrices velit tristique. Donec laoreet porttitor accumsan. Praesent adipiscing commodo leo, nec euismod est varius vitae. Praesent ac dolor tortor. Nunc lobortis semper neque, a luctus magna dapibus id.
<?php echo "\x00\x0A"; ?>
Quisque odio sapien, lobortis eu iaculis sed, ullamcorper sit amet eros. Suspendisse porta tortor vel dolor interdum condimentum. Aenean in nunc massa. In feugiat ornare turpis eget facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus et mattis mi. Aenean rhoncus elementum ullamcorper. Phasellus commodo sagittis felis at tincidunt. Proin sed orci libero. Nunc aliquet lacus non dolor bibendum dictum. In sit amet sapien diam, quis sollicitudin tortor. Aliquam ut orci vel libero aliquet dictum quis at erat.
<?php echo "\x00\x0A"; ?>
Ut lacus massa, tincidunt eu porta quis, sagittis tincidunt turpis. Phasellus luctus ligula at risus tincidunt id sagittis nulla dignissim. Aenean vitae magna libero. Pellentesque molestie imperdiet sapien et aliquet. Fusce laoreet, turpis ut feugiat gravida, tortor felis pellentesque nibh, in gravida eros neque in nunc. Maecenas rhoncus felis vel augue aliquet non molestie nisi posuere. Duis ligula orci, ornare et euismod sit amet, ultrices ac nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed eros lacus. Aliquam blandit est a elit lacinia ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean ornare, velit et mattis pulvinar, dolor augue placerat ipsum, non tristique sem felis vitae nulla. Integer dictum, turpis vel commodo adipiscing, est purus gravida diam, ac aliquam felis odio eget mi. Curabitur scelerisque lacus sit amet dui placerat in volutpat leo eleifend.
<?php echo "\x00\x0A"; ?>
Praesent ultrices dictum mauris ut pellentesque. Donec tincidunt bibendum sagittis. Sed elementum, lectus sed aliquam sodales, nisl ante luctus nunc, at ullamcorper lorem nisi ac nisi. Vestibulum laoreet mauris ac mi sodales nec volutpat orci pellentesque. Maecenas ut enim risus. Nullam mauris mauris, lobortis sed ultrices sed, lobortis quis eros. Quisque rhoncus, lorem nec elementum consectetur, velit libero pellentesque risus, id tristique neque diam non dui. Aenean dui ligula, volutpat eget lacinia vitae, facilisis sit amet nulla. Nulla iaculis magna et turpis euismod hendrerit. Praesent consectetur fermentum neque at dapibus. Proin id risus nunc, ac volutpat justo. Duis pulvinar turpis sit amet sem varius sit amet rutrum augue posuere. Donec pretium laoreet dui. Cras vitae orci nisi, id viverra elit. Vestibulum aliquam orci mattis ipsum egestas vitae ultrices urna semper. Pellentesque iaculis urna at ipsum fermentum sed volutpat neque bibendum.
<?php echo "\x00\x0A"; ?>
Vivamus ut odio id erat accumsan suscipit. Nulla id pellentesque est. Ut tortor velit, lobortis faucibus venenatis et, molestie a tortor. Nulla facilisi. Quisque eleifend bibendum facilisis. Aliquam non mauris at arcu pulvinar vestibulum a sit amet velit. Ut blandit pretium sollicitudin. Sed cursus felis ut sem auctor consectetur aliquam dolor feugiat.
<?php echo "\x00\x0A"; ?>
Pellentesque at metus et mi egestas rutrum quis vitae arcu. Donec sodales tristique nunc quis fringilla. Nulla a placerat ipsum. Suspendisse quis neque orci, et tempus tellus. Maecenas quis tortor quam. Cras in ipsum nisl. Maecenas non nulla sed nisi fringilla vestibulum sit amet quis odio. Nunc congue mattis rutrum.
<?php echo "\x00\x0A"; ?>
Nunc interdum, nibh in imperdiet molestie, dolor orci tempus leo, ut adipiscing nisl ipsum vitae leo. Etiam eros tortor, rutrum vel ullamcorper in, pretium vel nibh. Vestibulum elit purus, adipiscing at faucibus in, consequat sed mauris. Proin eleifend, justo vitae ullamcorper scelerisque, libero augue pulvinar dui, vitae porta ligula quam vel ligula. Nullam ut arcu erat, sed faucibus est. Integer bibendum urna molestie eros viverra venenatis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fermentum velit vitae ante dignissim lobortis. Integer lectus libero, viverra sit amet pellentesque sed, sagittis sit amet diam. Suspendisse sagittis risus id velit feugiat faucibus. Pellentesque a ligula quis odio porta viverra. Nullam interdum tempor consectetur.
<?php echo "\x00\x0A"; ?>
Quisque nec dolor a odio tincidunt elementum et sed quam. Etiam quis faucibus nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras eu sapien felis, in fringilla enim. Proin tellus mi, faucibus ut hendrerit et, aliquet sit amet sem. Nullam feugiat erat vel dui tempor pulvinar. Cras aliquam condimentum eleifend. Vivamus tempus rutrum tempus. In sodales libero non diam vulputate a ullamcorper ligula posuere. Suspendisse ultricies, ligula vel tincidunt consectetur, augue purus dignissim lacus, sed viverra tortor arcu nec metus. Quisque fringilla, quam gravida facilisis tincidunt, ante risus fermentum odio, sed accumsan magna dolor dignissim velit. Maecenas vitae nulla sed lacus hendrerit suscipit eget ac risus. Morbi blandit blandit quam non dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at nibh odio.
<?php echo "\x00\x0A"; ?>
Sed et purus turpis, non pretium elit. Nunc convallis commodo tellus, id bibendum est auctor nec. Maecenas eget tellus nisi. Donec rhoncus lacinia lectus pharetra euismod. Aliquam sit amet magna a velit vestibulum blandit eget at nulla. Proin sed sem mollis diam consequat accumsan et rhoncus magna. Suspendisse potenti. In hac habitasse platea dictumst. Aliquam vestibulum mauris et justo ultrices fringilla. Maecenas posuere vestibulum nibh non posuere. Ut euismod dictum consequat. Praesent sed purus lacus. Phasellus enim quam, condimentum lobortis pretium at, egestas in nisi. Sed ullamcorper tellus orci. Nunc in dui ac ipsum pellentesque fringilla. Mauris sit amet mauris nec urna rhoncus congue.
